[server]
headless = true
port = 8501
enableXsrfProtection = false
baseUrlPath = "webgrab"

[browser]
gatherUsageStats = false
serverAddress = "lucascode.org"
serverPort = 443

[client]
showErrorDetails = true
toolbarMode = "minimal"

[ui]
hideTopBar = false

[theme]
base = "dark"
primaryColor = "#58A6FF"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E6EDF3"
